loncra:
  basic-service:
    commons:
      app:
        operation-data-trace-entity-storage-count: 32
  framework:
    mvc:
      all-rest-result-format: true
    idempotent:
      ignore-classes: org.springframework.security.core.context.SecurityContext
    wechat:
      enabled: false
    mybatis:
      operation-data-trace:
        storage-position:
          prefix: ix_operation_data_trace
          spring-expression:
            - "T(io.github.loncra.framework.commons.ObjectUtils).getDimension(${loncra.basic-service.commons.app.operation-data-trace-entity-storage-count}, #target, T(java.util.Objects).toString(#entityId))"
    security:
      audit:
        type: elasticsearch
        storage-position:
          prefix: ix_audit_event
          spring-expression:
            - "T(io.github.loncra.framework.commons.DateUtils).dateFormat(#timestamp,'yyyy_MM_dd')"
            - "T(io.github.loncra.framework.commons.DateUtils).dateFormat(#creationTime,'yyyy_MM_dd')"
    authentication:
      plugin:
        generateSources: CONSOLE
        parent:
          config:
            application-name: commons
            name: "基础配置"
            type: root
            sources:
              - CONSOLE
          resource:
            application-name: commons
            name: "资源管理"
            type: root
            sources:
              - CONSOLE
          dictionary:
            application-name: resource-server
            name: "字典管理"
            parent: config
            type: menu
            sources:
              - CONSOLE
          organization:
            application-name: commons
            name: "机构管理"
            type: root
            sources:
              - CONSOLE
          authority:
            application-name: commons
            name: "权限管理"
            type: root
            sources:
              - CONSOLE
          log:
            application-name: commons
            name: "日志查询"
            type: root
            sources:
              - CONSOLE
          message:
            application-name: commons
            name: '消息管理'
            type: root
            sources:
              - CONSOLE
          workbench:
            name: "工作台"
            application-name: commons
            type: tool
            sources:
              - CONSOLE
          setting:
            name: "系统设置"
            application-name: commons
            type: profile
            sources:
              - CONSOLE
          my_message:
            name: "我的消息"
            application-name: commons
            type: tool
            sources:
              - CONSOLE
      ignore-audit-types:
        - AUTHENTICATION_FAILURE
        - AUTHORIZATION_FAILURE