package io.agentscope.extensions.model.ollama.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

@JsonIgnoreProperties(ignoreUnknown = true)
public class OllamaMessage {

    /** The role of the message sender (system, user, assistant, tool). */
    @JsonProperty("role")
    private String role;

    /** The content of the message. */
    @JsonProperty("content")
    private String content;

    /** List of base64-encoded images (optional). */
    @JsonProperty("images")
    private List<String> images;

    /** List of tool calls generated by the model (optional). */
    @JsonProperty("tool_calls")
    private List<OllamaToolCall> toolCalls;

    @JsonProperty("thinking")
    private String thinking;

    /** The tool call ID (required for tool messages). */
    @JsonProperty("tool_call_id")
    private String toolCallId;

    /** The name of the tool/function (optional/required for tool messages). */
    @JsonProperty("name")
    private String name;

    public OllamaMessage() {}

    public OllamaMessage(String role, String content) {
        this.role = role;
        this.content = content;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public List<String> getImages() {
        return images;
    }

    public void setImages(List<String> images) {
        this.images = images;
    }

    public List<OllamaToolCall> getToolCalls() {
        return toolCalls;
    }

    public void setToolCalls(List<OllamaToolCall> toolCalls) {
        this.toolCalls = toolCalls;
    }

    public String getToolCallId() {
        return toolCallId;
    }

    public void setToolCallId(String toolCallId) {
        this.toolCallId = toolCallId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    public String getThinking() { return thinking; }
    public void setThinking(String thinking) { this.thinking = thinking; }
}
