<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.loncra.basic.service</groupId>
    <artifactId>parent</artifactId>
    <name>parent</name>
    <version>2.0.0-SNAPSHOT</version>
    <description>parent pom</description>
    <packaging>pom</packaging>

    <url>https://github.com/loncra/basic-service.git</url>

    <developers>
        <developer>
            <id>chenxiaobo</id>
            <name>maurice.chen</name>
            <email>maurice.chen@foxmail.com.net</email>
            <timezone>+8</timezone>
        </developer>
    </developers>

    <scm>
        <url>https://github.com/loncra/basic-service.git.git</url>
        <connection>scm:git:ssh://git@github.com:loncra/basic-service.git</connection>
        <developerConnection>scm:git:ssh://git@github.com:loncra/basic-service.git</developerConnection>
        <tag>HEAD</tag>
    </scm>

    <repositories>
        <repository>
            <id>nexus-aliyun</id>
            <name>Nexus public Repository</name>
            <url>http://maven.aliyun.com/nexus/content/groups/public</url>
        </repository>
        <repository>
            <id>central-portal-snapshots</id>
            <name>Central Portal Snapshots</name>
            <url>https://central.sonatype.com/repository/maven-snapshots/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
        </repository>
    </repositories>

    <!--<distributionManagement>
        <repository>
            <id>sonatype</id>
            <name>Nexus Release Repository</name>
            <url>https://oss.sonatype.org/service/local/staging/deploy/maven2</url>
        </repository>
        <snapshotRepository>
            <id>sonatype</id>
            <name>Nexus Snapshot Repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </snapshotRepository>
    </distributionManagement>-->

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <loncra.framework.version>3.0.1-SNAPSHOT</loncra.framework.version>
        <loncra.ai.version>1.0.0-SNAPSHOT</loncra.ai.version>
        <agentscope.version>2.0.0</agentscope.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.encoding>UTF-8</maven.compiler.encoding>
    </properties>

    <dependencyManagement>

        <dependencies>

            <dependency>
                <groupId>io.github.loncra</groupId>
                <artifactId>framework-bom</artifactId>
                <version>${loncra.framework.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>io.github.loncra.basic.service</groupId>
                <artifactId>commons</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.loncra.basic.service</groupId>
                <artifactId>ai-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.loncra.basic.service</groupId>
                <artifactId>resource-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.loncra.basic.service</groupId>
                <artifactId>ai-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.loncra.basic.service</groupId>
                <artifactId>auth-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.loncra.basic.service</groupId>
                <artifactId>message-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>io.agentscope</groupId>
                <artifactId>agentscope-harness</artifactId>
                <version>${agentscope.version}</version>
            </dependency>

            <dependency>
                <groupId>io.agentscope</groupId>
                <artifactId>agentscope-extensions-model-dashscope</artifactId>
                <version>${agentscope.version}</version>
            </dependency>

            <dependency>
                <groupId>io.agentscope</groupId>
                <artifactId>agentscope-extensions-model-ollama</artifactId>
                <version>${agentscope.version}</version>
            </dependency>

            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-poi</artifactId>
                <version>5.8.35</version>
            </dependency>

            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml</artifactId>
                <version>5.4.1</version>
            </dependency>

            <dependency>
                <groupId>com.mysql</groupId>
                <artifactId>mysql-connector-j</artifactId>
                <version>9.7.0</version>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>1.18.42</version>
                <scope>provided</scope>
            </dependency>

        </dependencies>

    </dependencyManagement>

    <build>

        <finalName>${project.name}</finalName>

        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>

        <pluginManagement>
            <plugins>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.13.0</version>
                    <configuration>
                        <source>${maven.compiler.source}</source>
                        <target>${maven.compiler.target}</target>
                        <encoding>${project.build.sourceEncoding}</encoding>
                        <compilerArgs>
                            <arg>-parameters</arg>
                        </compilerArgs>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>3.3.3</version>
                    <configuration>
                        <classifier>spring-boot</classifier>
                        <finalName>${project.build.finalName}</finalName>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>repackage</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.5.0</version>
                    <configuration>
                        <argLine>-Dfile.encoding=${project.build.sourceEncoding}</argLine>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>3.3.1</version>
                    <configuration>
                        <encoding>${project.build.sourceEncoding}</encoding>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.4.0</version>
                    <configuration>
                        <archive>
                            <manifest>
                                <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                                <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
                            </manifest>
                        </archive>
                    </configuration>
                </plugin>

                <!--<plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>3.1.3</version>
                    <executions>
                        <execution>
                            <id>deploy</id>
                            <phase>deploy</phase>
                            <goals>
                                <goal>deploy</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>-->

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>3.3.1</version>
                    <executions>
                        <execution>
                            <id>attach-sources</id>
                            <goals>
                                <goal>jar-no-fork</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>3.10.0</version>
                    <dependencies>
                        <dependency>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.42</version>
                        </dependency>
                    </dependencies>
                    <configuration>
                        <encoding>${project.build.sourceEncoding}</encoding>
                        <charset>${project.build.sourceEncoding}</charset>
                        <docencoding>${project.build.sourceEncoding}</docencoding>
                    </configuration>
                    <executions>
                        <execution>
                            <id>attach-javadocs</id>
                            <phase>package</phase>
                            <goals>
                                <goal>jar</goal>
                            </goals>
                            <configuration>
                                <additionalJOption>-Xdoclint:none</additionalJOption>
                                <additionalOptions>
                                    <additionalOption>--ignore-source-errors</additionalOption>
                                </additionalOptions>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-release-plugin</artifactId>
                    <version>3.1.1</version>
                    <configuration>
                        <autoVersionSubmodules>true</autoVersionSubmodules>
                        <tagNameFormat>@{project.version}.release</tagNameFormat>
                        <mavenExecutorId>forked-path</mavenExecutorId>
                        <useReleaseProfile>false</useReleaseProfile>
                        <localCheckout>true</localCheckout>
                        <pushChanges>false</pushChanges>
                    </configuration>
                </plugin>

            </plugins>
        </pluginManagement>
    </build>

</project>